import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SessionClientProvider from '@/components/SessionProvider'
import { RoleContextProvider } from '@/components/context/RoleProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bidding App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <SessionClientProvider>
        <RoleContextProvider>
          <body className={inter.className}>
            <Navbar />
            <main className='min-h-screen container mx-auto px-4 pt-7  rounded-md'>{children}</main>
          </body>
        </RoleContextProvider>
      </SessionClientProvider>
    </html>
  )
}
